CREATE DATABASE noteapp;
USE noteapp;

CREATE TABLE tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE tasks
    ADD COLUMN title VARCHAR(255) NOT NULL,
    ADD COLUMN description TEXT NULL,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
    
ALTER TABLE tasks DROP COLUMN task;

ALTER TABLE tasks
ADD COLUMN pinned INT NOT NULL DEFAULT 0;

ALTER TABLE tasks
ADD COLUMN completed INT NOT NULL DEFAULT 0;